### PR TITLE
Allow setting the private and public keys

### LINKED ISSUE #4: Customize the IPs and private keys
I want an option to customize the IPs and wireguard keys for em_proxy while initialization.

Add 4 new optional paramater for em_proxy:
|  Name                                   | Default Value                                                                         |
|--------------------------------|-----------------------------------------------------------------|
| em_proxy server_privatekey  | UI+sCDEketXDq6vOAidLe0mYiHogMh1TA2zg3CqlxEA=     |
| em_proxy client_publickey     | ow01dGyrgRSrjln9bGb6fx0FwY5XKSVMTaoKQ2GDSkM=   |
| em_proxy server_ip                | 10.0.7.1                                                                                 |

make these value customizable instead of hardcoded in em_prixy
image
image

### PR DESCRIPTION
**Pull request by arthurmelton**
This should fix #4 and allow the program to set the public and private keys.

For the record I actually don't have a way to test this to see if it fully works, but I don't see any reason why this would not work. What confuses me is it feels like the IP address are pulled out of thin air, so I don't know if that is the case or if I am overlooking something.

### CODE REVIEW

**Comment by jkcoxson** [comment]
Thank you. 

The IPs are, in fact, pulled out of thin air. The way em_proxy works is it mirrors *any* request that ends up in the Wireguard tunnel. Line 329, mentioned in the issue, only assumes 10.7.0.1 to be a 'server' IP because that's what we decided, but it doesn't matter. What will determine if your packet reaches your device is what's in the Wireguard app assigned IP field.

**Comment by saltman007web** [comment]
pull

**Review by saltman007web — COMMENTED** [review]
review

**Review by saltman007web — COMMENTED** [review]
commit

**Pull request merged**
